apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gpa-backend
  namespace: gpa-prod
  labels:
    app.kubernetes.io/name: gpa-backend
    app.kubernetes.io/part-of: gpa-management
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpa-backend
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
