apiVersion: v1
kind: Service
metadata:
  name: gpa-backend
  namespace: gpa-staging
  labels:
    app.kubernetes.io/name: gpa-backend
    app.kubernetes.io/part-of: gpa-management
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gpa-backend
  ports:
    - name: http
      port: 5000
      targetPort: http
