apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gpa-gateway
  namespace: gpa-staging
  labels:
    app.kubernetes.io/part-of: gpa-management
spec:
  gatewayClassName: gpa-aws-alb
  infrastructure:
    parametersRef:
      group: gateway.k8s.aws
      kind: LoadBalancerConfiguration
      name: gpa-alb-config
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: api.<your-domain>
      allowedRoutes:
        namespaces:
          from: Same
