apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gpa-backend
  namespace: gpa-staging
  labels:
    app.kubernetes.io/name: gpa-backend
    app.kubernetes.io/part-of: gpa-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpa-backend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
