apiVersion: v1
kind: Secret
metadata:
  name: gpa-backend-secret
  namespace: gpa-staging
  labels:
    app.kubernetes.io/part-of: gpa-management
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://USER:PASSWORD@HOST/gpa-management"
  JWT_SECRET: "replace-with-at-least-32-random-characters"
  GOOGLE_CLIENT_ID: "replace-me"
  GOOGLE_CLIENT_SECRET: "replace-me"
  GOOGLE_CALLBACK_URL: "https://api.<your-domain>/api/auth/google/callback"
  EMAIL_USER: ""
  EMAIL_PASS: ""
