apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpa-worker
  namespace: gpa-staging
  labels:
    app.kubernetes.io/name: gpa-worker
    app.kubernetes.io/part-of: gpa-management
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gpa-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gpa-worker
        app.kubernetes.io/part-of: gpa-management
    spec:
      serviceAccountName: gpa-backend-sa
      containers:
        - name: gpa-worker
          image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/gpa-management-backend:<GIT_SHA>
          imagePullPolicy: IfNotPresent
          command: ["node", "worker.js"]
          envFrom:
            - configMapRef:
                name: gpa-backend-config
            - secretRef:
                name: gpa-backend-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
